### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by soniamontero**
@KateCatlin The revamp of the whole home page is done. 
It includes all the sections from Jamie's report and the draft language. 

It's fully working and responsive, improvements over details (interactivity to slide over the different sections, wording/language improvements, img/color choices, etc.) must be made later.

For the testimonials and the companies sections, I put some random img and text to have an accurate overview of what it will looks like when the fields will be correctly populated. Just need to change the path and the text, the result should be the same.

I didn't implement the last optional section ("Benefits and company culture") since it will entirely depends of later decisions about the language/wording improvements.

### CODE REVIEW

**Comment by KateCatlin** [comment]
This looks so good @soniamontero I'm dying of happiness. My heart is melting. Seriously it looks great. 
So a few changes: 

- Let's add back in the "It's all about benefits and company culture" section. I added notes to that on Trello. Sorry I missed your question before. 

- Let's take the companies section out for the moment. I want to double check with our actual companies that they're ok with us using their logos. I will add that to my personal Trello board to email Monday. 

- For the testimonials section, can you steal what's written under "They found their dream jobs" on the old Flock home page? https://www.findmyflock.com/. I'll also email recently placed candidates and see if we can get some more quotes. You can download their headshots:
https://www.linkedin.com/in/heatherdaymon/detail/photo/
https://www.linkedin.com/in/rachel-doren-121a15a1/detail/photo/
https://www.findmyflock.com/uploads/2/9/8/9/29890707/3_2_orig.png (maybe we can just crop out the writing part because I can't refind the picture)

**Comment by soniamontero** [comment]
Okay, I've added the section 6 with the company benefits. I made it as a 6 items list with a small description for each. I can make them shorter to be closer to the "list-design" you suggested at the beginning. What do you think? And oh! Please correct my English language/wording, I'm pretty sure there's a lot to change haha

I removed the section 5 with the companies' logo and C/c the code in a file named "to_add_later" inside the view. Maybe not the best practice but, it's here ready to be added back if needed!

The real testimonials have been added too.

The buttons on the home page (Log In and Join) are now changing to "My Profile" and "Job Dashboard"  when current_user. We can also remove them actually

**Comment by KateCatlin** [comment]
Looks great. I made a few wording changes, but I think this is good to let fly and see how people react. Merging!

**Comment by KateCatlin** [comment]
Hey sorry @soniamontero I talked this over with Jaime and it seems we envisioned the last section ("BENEFITS AND COMPANY CULTURE") pretty differently. So rather than reiterating all our differentiators, it's just a list. Like a bullet-point list of all the items we have listed on the benefits dropdown. So people can see the types of things they could limit their searches by.

So that's one last change! 

Also it's now showing a merge conflict and I'm very confused why as there is no merge conflict on my branch when I pull it down...

**Comment by soniamontero** [comment]
Section 6 updated as a list of benefits.

**Comment by KateCatlin** [comment]
Added a quick push to solve merge conflicts. Not sure where they came from but gone now. Everything functioning and beautiful. I am SO EXCITED TO PUSH THIS TO HEROKU!

**Pull request merged**
