### PR TITLE
Responsive edit profile

### PR DESCRIPTION
**Pull request by soniamontero**

### CODE REVIEW

**Comment by KateCatlin** [comment]
Hey @soniamontero looks great! Question though: I no longer shows the 'tabs' user flow to buttons, instead all 6 options are displayed and are highlighted orange when we're on it. Totally cool if that's an intentional design choice. Just want to make sure we're conscientiously making that change.

**Comment by soniamontero** [comment]
Yep, it’s intentional. I tried to keep the tabs and stack them in column, on the upper part or on the left of the form, but none of these options were conclusive. This is the cleanest way I found to make it fully responsive - we can definitely talk about it if you don’t agree in this design/choice of color - I’m not married to the concept!

**Comment by soniamontero** [comment]
@KateCatlin Yep, it’s intentional. I tried to keep the tabs and stack them in column, on the upper part or on the left of the form, but none of these options were conclusive. This is the cleanest way I found to make it fully responsive - we can definitely talk about it if you don’t agree in this design/choice of color - I’m not married to the concept!

**Comment by KateCatlin** [comment]
Sweet! I trust your judgment and think it looks great!

**Pull request merged**
