### PR TITLE
Ajax favorites

### PR DESCRIPTION
**Pull request by skiffb**
should be able to favorite and unfavorite between the three tabs on the dashboard...was thinking maybe could rebuild bootstrap grid every time one is deleted in the favorties tab at some point?

### CODE REVIEW

**Comment by KateCatlin** [comment]
Hey @skiffb I've tried pulling this branch down to test it 2x, and it's not working for me. The favorite/unfavorite button doesn't seem to trigger any branches, and it's caused the job boards to get wild like a La Favela dance party 💃.  Sending you some screenshots on Slack. Can you test it again on your machine and see if it does the same thing?

**Comment by KateCatlin** [comment]
Also, yes, happy to leave time in sprint 2 for technical debt like this. I know Sonia wants to spend some time cleaning up the CSS as well. Good time for a step back before a step forward kinda thing.

**Comment by skiffb** [comment]
so i resolved the merge conflict (and hopefully didn't delete any of sonia's changes) and it is working fine on my machine in addition to the recent changes. Does it work better for you now?

**Comment by KateCatlin** [comment]
Look perfect and is functioning now, thank you!

**Pull request merged**
